import pygame as pg


pg.init()
pg.font.init()


#Calculates maze dimensions in number of cells
K_WIDTH = 21
K_HEIGHT = 9
MIN_MAZE_HEIGHT = 3
MIN_MAZE_WIDTH = 3
MAX_MAZE_WIDTH = 3 + 2 * K_WIDTH
MAX_MAZE_HEIGHT = 3 + 2 * K_HEIGHT
MAX_EDGE_WEIGHT = 30

#Dimmensions of UI in pixels
CELL_WIDTH = 15 
SIDEBAR_WIDTH = 400
MAX_GRAPHICAL_MAZE_WIDTH = MAX_MAZE_WIDTH * CELL_WIDTH
WINDOW_HEIGHT = MAX_MAZE_HEIGHT * CELL_WIDTH
WINDOW_WIDTH = MAX_GRAPHICAL_MAZE_WIDTH + SIDEBAR_WIDTH

#Frames per second
FPS = 10

#The slider boxes dimmensions
SLIDER_BOX_WIDTH = WINDOW_HEIGHT // 16
SLIDER_THICKNESS = WINDOW_HEIGHT // 32
BOX_X_CORD = MAX_GRAPHICAL_MAZE_WIDTH  + SIDEBAR_WIDTH // 2 - SLIDER_BOX_WIDTH // 2
FONT_SIZE = int((30/800) * WINDOW_HEIGHT) #Size of text in box

#The sliders dimmensions
SLIDER_X_CORD = SIDEBAR_WIDTH // 5 + MAX_GRAPHICAL_MAZE_WIDTH
WIDTH_SLIDER_Y_CORD = WINDOW_HEIGHT // 5
HEIGHT_SLIDER_Y_CORD = WINDOW_HEIGHT * 2 // 5
SLIDER_LENGTH = SIDEBAR_WIDTH * 3 // 5

#Colors
SIDEBAR_COLOR = (170,100,100)
BACKGROUND_COLOR = (0,0,0)
MAZE_COLORS = ((0,0,0), (255,120,120), (255,255,255), (150,0,0), (0,150,0))
START_BUTTON_COLOR = (100,200,100)
RESET_BUTTON_COLOR = (120,120,255)
BUTTON_TEXT_COLOR = (0,0,0)

#Indices corresponding to a color value in MAZE_COLORS
WALL = 0
UNDECIDED = 1
PATH = 2
EDGE_BEING_PROCESSED = 3
CONNECTION_BEING_PROCESSED= 4

#General button Variables
FONT = pg.font.SysFont("Arial", FONT_SIZE)
BUTTON_HEIGHT = int(FONT_SIZE * 1.5)

#Start button variables
START_BUTTON_TEXT = "START"
START_BUTTON_WIDTH = FONT_SIZE * len(START_BUTTON_TEXT) 
START_BUTTON_X_CORD = MAX_GRAPHICAL_MAZE_WIDTH + SIDEBAR_WIDTH // 5
START_BUTTON_Y_CORD = WINDOW_HEIGHT *3 // 5

#Reset button variables
RESET_BUTTON_TEXT = "RESET"
RESET_BUTTON_WIDTH = FONT_SIZE * len(RESET_BUTTON_TEXT) 
RESET_BUTTON_X_CORD = MAX_GRAPHICAL_MAZE_WIDTH + SIDEBAR_WIDTH // 2
RESET_BUTTON_Y_CORD = WINDOW_HEIGHT * 3 // 5

#Contrains window dimmensions to fiesable size
assert 0 <= WINDOW_HEIGHT <= 700 , "WINDOWHEIGHTERROR: Choose smaller K_HEIGHT value."
assert 0 <= WINDOW_WIDTH <= 1300, "WINDOWWIDTHERROR: Choose smaller K_WIDTH value."