
#Calculates maze dimensions in number of cells
K_WIDTH = 30
K_HEIGHT = 12
MIN_MAZE_HEIGHT = 3
MIN_MAZE_WIDTH = 3
MAX_MAZE_WIDTH = 3 + 2 * K_WIDTH
MAX_MAZE_HEIGHT = 3 + 3 * K_HEIGHT

#Dimmensions of UI in pixels
CELL_WIDTH = 15 
SIDEBAR_WIDTH = 200
MAX_GRAPHICAL_MAZE_WIDTH = MAX_MAZE_WIDTH * CELL_WIDTH
WINDOW_HEIGHT = MAX_MAZE_HEIGHT * CELL_WIDTH
WINDOW_WIDTH = MAX_GRAPHICAL_MAZE_WIDTH + SIDEBAR_WIDTH

#Frames per second
FPS = 10

#The slider boxes dimmensions
SLIDER_BOX_WIDTH = WINDOW_HEIGHT // 16
SLIDER_THICKNESS = WINDOW_HEIGHT // 32
BOX_X_CORD = MAX_GRAPHICAL_MAZE_WIDTH  + SIDEBAR_WIDTH // 2 - SLIDER_BOX_WIDTH // 2
FONT_SIZE = int((30/800) * WINDOW_HEIGHT) #Size of text in box

#The sliders dimmensions
SLIDER_X_CORD = SIDEBAR_WIDTH // 5 + MAX_GRAPHICAL_MAZE_WIDTH
WIDTH_SLIDER_Y_CORD = WINDOW_HEIGHT // 4
HEIGHT_SLIDER_Y_CORD = WINDOW_HEIGHT // 2
SLIDER_LENGTH = SIDEBAR_WIDTH * 3 // 5

#Colors
SIDE_BAR_COLOR = (200,100,100)
MAZE_COLORS = ((0,0,0), (0,150,150), (255,255,255),(150,0,0), (0,150,0))

#Indices corresponding to a color value in MAZE_COLORS
WALL = 0
UNDECIDED = 1
PATH = 2
EDGE_BEING_PROCESSED = 3
CONNECTION_BEING_PROCESSED= 4

#Contrains window dimmensions to fiesable size
assert 0 <= WINDOW_HEIGHT <= 700 , "WINDOWHEIGHTERROR"
assert 0 <= WINDOW_WIDTH <= 1200, "WINDOWWIDTHERROR"